services:
  backend:
    restart: unless-stopped
    working_dir: /app/backend
    ports: ["8000:8000"]
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      REDIS_URL: redis://redis:6379/0
      PYTHONPATH: /app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      bash -lc "python -m uvicorn main:app --host 0.0.0.0 --port 8000 --log-level info"
  db:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
  redis:
    image: redis:7-alpine
