version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:2.14.2-pg15
    container_name: timescaledb
    restart: always
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: trader123
      POSTGRES_DB: marketdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
